consistent(X) :- has_shape(X, triangle), has_color(X, red), has_label(X, pedestrian_crossing), sign(X) . 
consistent(X) :- has_shape(X, circle), has_color(X, red), has_label(X, speed_limit_20), sign(X) . 
consistent(X) :- has_shape(X, circle), has_color(X, red), has_label(X, speed_limit_30), sign(X) . 
consistent(X) :- has_shape(X, circle), has_color(X, red), has_label(X, no_overtaking_trucks), sign(X) . 
consistent(X) :- has_shape(X, triangle), has_color(X, red), has_label(X, priority_at_next_intersection), sign(X) . 
consistent(X) :- has_shape(X, square), has_color(X, yellow), has_label(X, priority_road), sign(X) . 
consistent(X) :- has_shape(X, inverse_triange), has_color(X, red), has_label(X, give_way), sign(X) . 
consistent(X) :- has_shape(X, octagon), has_color(X, red), has_label(X, stop), sign(X) . 
consistent(X) :- has_shape(X, circle), has_color(X, red), has_label(X, no_traffic_both_ways), sign(X) . 
consistent(X) :- has_shape(X, circle), has_color(X, red), has_label(X, no_trucks), sign(X) . 
consistent(X) :- has_shape(X, circle), has_color(X, red), has_label(X, no_entry), sign(X) . 
consistent(X) :- has_shape(X, triangle), has_color(X, red), has_label(X, danger), sign(X) . 
consistent(X) :- has_shape(X, triangle), has_color(X, red), has_label(X, bend_left), sign(X) . 
consistent(X) :- has_shape(X, circle), has_color(X, red), has_label(X, speed_limit_50), sign(X) . 
consistent(X) :- has_shape(X, triangle), has_color(X, red), has_label(X, bend_right), sign(X) . 
consistent(X) :- has_shape(X, triangle), has_color(X, red), has_label(X, bend), sign(X) . 
consistent(X) :- has_shape(X, triangle), has_color(X, red), has_label(X, uneven_road), sign(X) . 
consistent(X) :- has_shape(X, triangle), has_color(X, red), has_label(X, slippery_road), sign(X) . 
consistent(X) :- has_shape(X, triangle), has_color(X, red), has_label(X, road_narrows), sign(X) . 
consistent(X) :- has_shape(X, triangle), has_color(X, red), has_label(X, construction), sign(X) . 
consistent(X) :- has_shape(X, triangle), has_color(X, red), has_label(X, traffic_signal), sign(X) . 
consistent(X) :- has_shape(X, triangle), has_color(X, red), has_label(X, school_crossing), sign(X) . 
consistent(X) :- has_shape(X, triangle), has_color(X, red), has_label(X, cycles_crossing), sign(X) . 
consistent(X) :- has_shape(X, circle), has_color(X, red), has_label(X, speed_limit_60), sign(X) . 
consistent(X) :- has_shape(X, triangle), has_color(X, red), has_label(X, snow), sign(X) . 
consistent(X) :- has_shape(X, triangle), has_color(X, red), has_label(X, animals), sign(X) . 
consistent(X) :- has_shape(X, circle), has_color(X, white), has_label(X, restriction_ends), sign(X) . 
consistent(X) :- has_shape(X, circle), has_color(X, blue), has_label(X, go_right), sign(X) . 
consistent(X) :- has_shape(X, circle), has_color(X, blue), has_label(X, go_left), sign(X) . 
consistent(X) :- has_shape(X, circle), has_color(X, blue), has_label(X, go_straight), sign(X) . 
consistent(X) :- has_shape(X, circle), has_color(X, blue), has_label(X, go_right_or_straight), sign(X) . 
consistent(X) :- has_shape(X, circle), has_color(X, blue), has_label(X, go_left_or_straight), sign(X) . 
consistent(X) :- has_shape(X, circle), has_color(X, blue), has_label(X, keep_right), sign(X) . 
consistent(X) :- has_shape(X, circle), has_color(X, blue), has_label(X, keep_left), sign(X) . 
consistent(X) :- has_shape(X, circle), has_color(X, red), has_label(X, speed_limit_70), sign(X) . 
consistent(X) :- has_shape(X, circle), has_color(X, blue), has_label(X, roundabout), sign(X) . 
consistent(X) :- has_shape(X, circle), has_color(X, white), has_label(X, restriction_ends_overtaking), sign(X) . 
consistent(X) :- has_shape(X, circle), has_color(X, white), has_label(X, restriction_ends_overtaking_trucks), sign(X) . 
consistent(X) :- has_shape(X, circle), has_color(X, red), has_label(X, speed_limit_80), sign(X) . 
consistent(X) :- has_shape(X, circle), has_color(X, white), has_label(X, restriction_ends_80), sign(X) . 
consistent(X) :- has_shape(X, circle), has_color(X, red), has_label(X, speed_limit_100), sign(X) . 
consistent(X) :- has_shape(X, circle), has_color(X, red), has_label(X, speed_limit_120), sign(X) . 
consistent(X) :- has_shape(X, circle), has_color(X, red), has_label(X, no_overtaking), sign(X) . 
